import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "IMS | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className="">
        <Header />
        {children}
        <Footer/>    
      </body>
    </html>
  );
}
